### ISSUE TITLE
:sparkles: Add support for container restart policy

### ISSUE THREAD

**Issue by linkdd** [SaaShup/netbox-docker-plugin#101]
| Netbox version | Plugin version | Agent version |  Docker API Version |
| --- | --- | --- | --- |
| 3..6.9 | 1.2.0 | N/A | N/A |

## Actual Behavior

There is no way to specify a restart policy on a container. This means for example, that when the host restarts, the `netbox-docker-agent` is not restarted automatically, and you can't restart it from Netbox since the agent is not there to start it (oopsie).

## Desired Behavior

According to [the documentation](https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy), we can configure a container to be restarted:

 - `no`: never
 - `on-failure[:max-retries]`: when it crashes (retry at least `max-retries`)
 - `always`: which is what you would want for the `netbox-docker-agent` container
 - `unless-stopped`: same as `always` except if manually stopped

A field should be added to the `Container` model, as an enumeration, to define the restart policy. The default value should be `no`.
Another field should be added for the `max-retries` as well.

**Comment by fanshan** [comment]
@linkdd We will first implement the enumeration. We plan for later the `max-retries` property.
