### ISSUE TITLE
delete a running container

### ISSUE THREAD

**Issue by lvenier** [SaaShup/netbox-docker-plugin#119]
| Netbox version | Plugin Version | Agent version |  Docker API Version |
| --- | --- | --- | --- |
|  3.7.1 | 1.6.2 | 20.0 | 1.43 |

## Actual Behavior

Today it is possible to request to delete a running container in the plugin but it raises an error in the agent :

 {"message":"You cannot remove a running container d199e8e066f49321ddea958aa8bfe20285f563e0140090fa80ea491e905de3f9. Stop the container before attempting removal or force remove"}

## Desired Behavior

Possible options are : 
- prevent deletion running container from the plugin
- force stop before deletion in the agent

opinions welcome

**Comment by dzove855** [comment]
I would implement the feature inside the plugin. We should not force a stop in the agent if it's not asked to do so

The agent should only do what it is asked for and not implement some hidden tasks
