### ISSUE TITLE
Container's host should not be changed

### ISSUE THREAD

**Issue by fanshan** [SaaShup/netbox-docker-plugin#122]
| Netbox version | Plugin Version | Agent version |  Docker API Version |
| --- | --- | --- | --- |
| 3.7.* | 1.8.0 | * | * |

## Actual Behavior

Container's host can be changed. This mean if we set multiple hosts on one Netbox instance, we can update a Container with a host changed. User can be confuse by this behaviour because the Container will not be delete on the former Host and not created on the new host.

## Desired Behavior

For now, remove the possibility to change the container's host.

**Comment by linkdd** [comment]
Netbox has [custom scripts](https://github.com/netbox-community/netbox/blob/develop/docs/customization/custom-scripts.md) which could be used here to:

1. create the container on the new host
2. remove the container on the old host (if creation was successful)

By sending the proper request to the agents.
