### ISSUE TITLE
Container public port unexpected behavior.

### ISSUE THREAD

**Issue by somediego** [SaaShup/netbox-docker-plugin#168]
| Netbox version | Plugin Version | Agent version |  Docker API Version |
| --- | --- | --- | --- |
| 4.1.6 | v3.1.0(I believe) | 1.5.5 | 1.47 |

## Actual Behavior

Hello,  

When a container has no public port and shows as in the picture. 
```
public port:0
private port: 3456
```
![test](https://github.com/user-attachments/assets/a59fceb1-c138-4c62-aaa2-fc7bc915d08e)
After push recreate, it will give to the image a random public port.
And even if I write back external port with value '0', and recreate again, it will always have an external port.

## Desired Behavior
I would love to click recreate, and no port changes without reason.

## Nice to have
I would love to remove public exposure of port if possible, now it does work now. `recreate` always expose.

**Comment by fanshan** [comment]
Fixed by https://github.com/SaaShup/netbox-docker-agent/pull/168
