### ISSUE TITLE
Create Host API call fails

### ISSUE THREAD

**Issue by vamitrou** [SaaShup/netbox-docker-plugin#171]
| Netbox version | Plugin Version | Agent version |  Docker API Version |
| --- | --- | --- | --- |
| 3.6.9 |  | 1.6.1 | 1.45 |

## Actual Behavior

When executing a create host API call it gives me an HTTP_ORIGIN error.

curl -X POST -H "Authorization: Token xxxxx" -H "Content-Type: application/json" \
    https://myhost/api/plugins/docker/hosts/  -d \
        '{"name": "test-add", "endpoint": "https://xxxx:xxxx@test.com:1990"}'
 
 
{"error": "'HTTP_ORIGIN'", "exception": "KeyError", "netbox_version": "3.6.9", "python_version": "3.11.4"}

## Desired Behavior

The request should succeed and return the properties of the created object.

**Comment by vamitrou** [comment]
Adding the Origin header worked. It's not needed in other API endpoints.

**Comment by fanshan** [comment]
> Adding the Origin header worked. It's not needed in other API endpoints.

The Origin header is only need for adding a new host. We will update the README file in order to consign this point.

**Comment by lvenier** [comment]
README has been updated : https://github.com/SaaShup/netbox-docker-plugin/pull/172
