### ISSUE TITLE
network-settings not exposed via API

### ISSUE THREAD

**Issue by vamitrou** [SaaShup/netbox-docker-plugin#173]
| Netbox version | Plugin Version | Agent version |  Docker API Version |
| --- | --- | --- | --- |
| 3.6.9 |  | 1.6.1 | 1.45 |

## Actual Behavior

When trying to access/modify the network-settings via the API at https://mynetbox/api/plugins/docker/network-settings/ I am receiving a 404.

## Desired Behavior

I would need this endpoint so I can change the network settings of my container to `host`.  If is possible to do this during creation time it would be OK as a workaround.

**Comment by lvenier** [comment]
@vamitrou if you want to change the network settings to a container you need to the go through the PATCH /api/plugins/docker/containers/{id}/ and provide the network settings in the payload you want to apply.
Is that what you are trying to achieve ?

**Comment by vamitrou** [comment]
this has worked. thank you.
