### ISSUE TITLE
add webhooks during plugin setup

### ISSUE THREAD

**Issue by lvenier** [SaaShup/netbox-docker-plugin#53]
I guess webhooks I can added in the plugin setup.
pls find below the current webhooks definition.

[netbox_webhooks_0.0.1.csv](https://github.com/SaaShup/netbox-docker-plugin/files/13988868/netbox_webhooks_0.0.1.csv)

Carefull this is an export for netbox version < 3.7.0

**Comment by dzove855** [comment]
Hello,

Please find below the real csv file which is working in netbox <3.7

[netbox_webhooks.csv](https://github.com/SaaShup/netbox-docker-plugin/files/14096024/netbox_webhooks.csv)
