### ISSUE TITLE
Host endpoints passwords are visible

### ISSUE THREAD

**Issue by fanshan** [SaaShup/netbox-docker-plugin#62]
When we add an Host with an endpoint that need password, this password is actually visible on Host list.

Exemple: http://user:pass@10.10.10.1:1880

this endpoint should be visible like:
http://user:***@10.10.10.1:1880

Open question: how to print Host endpoint with password on edition form?

**Comment by lvenier** [comment]
Best would be to change the host url.
Why not when we create a host request host (from the vm list ? ), port (from the service ?), login, password, protocol (http/https)....

**Comment by fanshan** [comment]
@lvenier can we link a host with this kind of service?

<img width="985" alt="image" src="https://github.com/SaaShup/netbox-docker-plugin/assets/1986015/42b02ffb-ac19-4138-b0f8-235438563cef">
