### ISSUE TITLE
Image version

### ISSUE THREAD

**Issue by fanshan** [SaaShup/netbox-docker-plugin#69]
Depending on registry, the Image version is not good.
![image](https://github.com/SaaShup/netbox-docker-plugin/assets/1986015/0646cd86-0c6d-43c0-aaeb-e30ee685ba76)

**Comment by lvenier** [comment]
@dzove855 @fanshan this issue has been solved with agent latest version ?

**Comment by dzove855** [comment]
This should have been fixed with this pr: https://github.com/SaaShup/netbox-docker-agent/pull/43

**Comment by fanshan** [comment]
> This should have been fixed with this pr: [SaaShup/netbox-docker-agent#43](https://github.com/SaaShup/netbox-docker-agent/pull/43)

Yes
