### ISSUE TITLE
Certificates plugin?

### ISSUE THREAD

**Issue by deku-m** [SaaShup/netbox-docker-plugin#92]
Hi,

Sorry this isnt related to your plugin.
But in your screenshot i saw that you have a some sort of certificates plugin.
Do you know where i can find it?

Thanks.

**Comment by dzove855** [comment]
Hello,

You can find the plugin in https://code.europa.eu/digit-c4/netbox/netbox-cert-plugin


Actually we use netbox at the european commission with various plugins and some more will come in the future.

https://code.europa.eu/digit-c4/netbox/

**Comment by deku-m** [comment]
Ooh very nice thank you
